<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3activity\models\base;

use Yii;
use d3system\behaviors\D3DateTimeBehavior;

/**
 * This is the base-model class for table "d3a_last_notification".
 *
 * @property string $id
 * @property integer $sys_company_id
 * @property string $time
 * @property string $aliasModel
 */
abstract class D3aLastNotification extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3a_last_notification';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        $behaviors = array_merge(
            $behaviors,
            D3DateTimeBehavior::getConfig(['time'])
        );
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_company_id'], 'required'],
            'smallint Unsigned' => [['sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'bigint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 1.844674407371E+19],
            [['time'], 'safe'],
            'D3DateTimeBehavior' => [['time_local'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('docreg', 'ID'),
            'sys_company_id' => Yii::t('docreg', 'Sys Company ID'),
            'time' => Yii::t('docreg', 'Time'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3activity\models\D3aLastNotificationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3activity\models\D3aLastNotificationQuery(get_called_class());
    }

}
