<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3activity\models\base;

use Yii;


/**
 * This is the base-model class for table "d3d_action_label".
 *
 * @property integer $id
 * @property integer $action_id
 * @property string $language
 * @property string $label
 *
 * @property \d3yii2\d3activity\models\D3aAction $action
 * @property string $aliasModel
 */
abstract class D3DActionLabel extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3d_action_label';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['action_id'], 'required'],
            'smallint Unsigned' => [['action_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['language'], 'string', 'max' => 25],
            [['label'], 'string', 'max' => 255],
            [['action_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3activity\models\D3aAction::className(), 'targetAttribute' => ['action_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('docreg', 'ID'),
            'action_id' => Yii::t('docreg', 'Action ID'),
            'language' => Yii::t('docreg', 'Language'),
            'label' => Yii::t('docreg', 'Label'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'language' => Yii::t('docreg', 'Language'),
            'label' => Yii::t('docreg', 'Label'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAction()
    {
        return $this->hasOne(\d3yii2\d3activity\models\D3aAction::className(), ['id' => 'action_id'])->inverseOf('d3dActionLabels');
    }




}
